### ISSUE TITLE
Add key and value arguments to get_geofabric

### ISSUE THREAD

**Issue by Robinlovelace** [ITSLeeds/geofabrik#30]

**Comment by Robinlovelace** [comment]
Done for now. Not perfect but works. I suspect that an alternative approach, writing a function to generate valid queries, e.g. called `gf_query()` may be better, as discussed in #31 .

**Comment by agila5** [comment]
I know that I should have said this a few weeks ago (sorry about that, I totally forgot about this package) but, IMO, we should code a generic query approach for `read_pbf` function and the "..." approach is the easiest one. The problem with the current approach is that it doesn't allow the creation of generic queries like:  `select * from lines where max_speed > 30` or `select * from lines where highway in c("a", "b")` or countless other examples. 

What do you think? We can discuss this again after fixing #7.

**Comment by Robinlovelace** [comment]
I think your suggested approach is good Andrea, although the most intuitive apporach could be something like:

```r
read_pbf(f, max_speed > 30 | highway == "a|b")
```

Or similar...

A modular approach could be something like

```r
q = gf_query(max_speed > 30 | highway == "a|b")
read_pbf(f, query = q)
```

I can see pros and cons of each approach (and alternative approaches including using `translate_sql()` described in https://dbplyr.tidyverse.org/articles/sql-translation.html ) that peer review could help us decide on. In the meantime, I'm sure that changes to this could make it more user friendly in the near-term so happy for you ena
