### ISSUE TITLE
Package name

### ISSUE THREAD

**Issue by mem48** [ITSLeeds/geofabrik#32]
geofabric or geofabrik https://www.geofabrik.de/data/download.html

**Comment by Robinlovelace** [comment]
Personally I like geofabric. It's a cool name its own right (for downloading OSM data, the fabric of open geo data) but not too tied to the geofabik service, an ideal balance IMO that would still stand if that service went down.

**Comment by Robinlovelace** [comment]
Thoughts @agila5 ?

**Comment by agila5** [comment]
I would change the package name to "geofabrik" or "geofabRik" or something like that. I don't see any problem changing the package name since there are just a few people using it atm. 

> Personally I like geofabric. It's a cool name its own right (for downloading OSM data, the fabric of open geo data) but not too tied to the geofabik service, an ideal balance IMO that would still stand if that service went down.

The core idea behind the package is downloading data from geofabrik servers so I don't see the point of this package if that service goes down.

**Comment by Robinlovelace** [comment]
Happy to change the name, looks like I've been outvoted! PRs welcome. However this raises the wider question: should we submit this for peer review to rOpenSci. I guess that depends on how much we want to work on it to complete the review. Will almost certainly make the package more user friendly if it does get a peer review. Thoughts?

**Comment by agila5** [comment]
> Happy to change the name, looks like I've been outvoted! PRs welcome.

Working on that. 

> However this raises the wider question: should we submit this for peer review to rOpenSci

IMO, yes! I can't focus on this project until mid february but I'd like to submit it for peer review.

**Comment by Robinlovelace** [comment]
Re-opening this following the discovery that there are other good extract providers as documented in #38  and discussion with @maelle and others from rOpenSci shown below.

My suggestion in https://github.com/ITSLeeds/geofabrik/issues/32 was for the package not to be tied to geofabrik and I think that is a good idea. The package could evolve to include other bulk sources.

I could think of worse names than geofabric for a generic package to dl osm data. If we were to generalise the package, how about **osmextract**?

> 👍  for {osmextract} (from what I understand the package does / is supposed to do).

**Comment by Robinlovelace** [comment]
Update: I think we should rename it to `osmextractr` and will open a PR that implements that.

**Comment by Robinlovelace** [comment]
Example for readme: 

![image](https://user-images.githubusercontent.com/1825120/87085554-f77e8b00-c227-11ea-914a-936b8be23132.png)
